<a href="https://colab.research.google.com/github/dipanwitad-create/NASSCOM_FDP_programme/blob/main/Day2NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

# ----------------------------
# Task 1: Array Creation
# ----------------------------
arr1_1 = np.arange(100)
arr1_2 = np.ones((3, 3))
arr1_3 = np.full((2, 4), 7)
arr1_4 = np.random.randint(10, 51, size=(5, 5))





In [14]:
# ----------------------------
# Task 2: Indexing and Slicing
# ----------------------------
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

val2_1 = data[2, 3]
row2_2 = data[0]
col2_3 = data[:, -1]
sub_arr2_4 = data[1:3, 0:2]
filtered_elements2_5 = data[data > 100]
print("\nTask 2 Results")
print("val2_1 =", val2_1)
print("row2_2 =", row2_2)
print("col2_3 =", col2_3)
print("sub_arr2_4 =\n", sub_arr2_4)
print("filtered_elements2_5 =", filtered_elements2_5)











Task 2 Results
val2_1 = 120
row2_2 = [10 20 30 40]
col2_3 = [ 40  80 120 160]
sub_arr2_4 =
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5 = [110 120 130 140 150 160]


In [15]:
# ----------------------------
# Task 3: Conditional Operations
# ----------------------------
arr3_1 = np.random.randint(1, 21, size=(4, 5))

arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

even_count3_3 = np.sum(arr3_1 % 2 == 0)
print("\nTask 3 Results")
print("arr3_2 =\n", arr3_2)
print("Even Count =", even_count3_3)


Task 3 Results
arr3_2 =
 [[12 15 16  0  0]
 [ 0  0 17  0  0]
 [ 0  0  0 11 12]
 [18 18  0 16 15]]
Even Count = 7


In [16]:
# ----------------------------
# Task 4: Aggregation Functions
# ----------------------------
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

sum4_1 = np.sum(arr4_1)

mean_cols4_2 = np.mean(arr4_1, axis=0)

max_rows4_3 = np.max(arr4_1, axis=1)

std4_4 = np.std(arr4_1)
print("\nTask 4 Results")
print("Sum =", sum4_1)
print("Column Means =", mean_cols4_2)
print("Row Maximums =", max_rows4_3)
print("Standard Deviation =", std4_4)


Task 4 Results
Sum = 84
Column Means = [11.          6.66666667 10.33333333]
Row Maximums = [12 15 20]
Standard Deviation = 5.2493385826745405


In [17]:
# ----------------------------
# Task 5: Reshaping and Flattening
# ----------------------------
arr5_1 = np.arange(24)

reshaped_arr5_2 = arr5_1.reshape(4, 6)

reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

flattened_arr5_4 = reshaped_arr5_2.flatten()

# Alternative:
# flattened_arr5_4 = reshaped_arr5_2.ravel()

print("\nTask 5 Results")
print("4x6 Shape =\n", reshaped_arr5_2)
print("2x3x4 Shape =\n", reshaped_arr5_3)
print("Flattened =", flattened_arr5_4)


Task 5 Results
4x6 Shape =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
2x3x4 Shape =
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Flattened = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [18]:
# ----------------------------
# Task 6: Broadcasting
# ----------------------------
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

result6_1 = arr6_1 + scalar

result6_2 = arr6_1 + vector
print("\nTask 6 Results")
print("Scalar Addition =\n", result6_1)
print("Vector Addition =\n", result6_2)


Task 6 Results
Scalar Addition =
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Vector Addition =
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [19]:
# ----------------------------
# Task 7: Copying vs Viewing
# ----------------------------
original_arr7 = np.array([1, 2, 3, 4, 5])

view_arr7 = original_arr7[:]
view_arr7[0] = 99

copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("Original Array:", original_arr7)
print("View Array:", view_arr7)
print("Copy Array:", copy_arr7)

Original Array: [99  2  3  4  5]
View Array: [99  2  3  4  5]
Copy Array: [99  2  3  4  0]


In [20]:
# ----------------------------
# Task 8: Stacking and Splitting
# ----------------------------
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

part1, part2, part3 = np.array_split(combined_arr8_3, 3)
print("\nTask 8 Results")
print("Vertical Stack =\n", vstack_arr8_1)
print("Horizontal Stack =\n", hstack_arr8_2)
print("Combined Array =\n", combined_arr8_3)


Task 8 Results
Vertical Stack =
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack =
 [[1 2 5 6]
 [3 4 7 8]]
Combined Array =
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [21]:
# ----------------------------
# Task 9: Sorting and Searching
# ----------------------------
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

sorted_arr9_1 = np.sort(arr9_1)

sorted_cols9_2 = np.sort(arr9_2d, axis=0)

idx9_3 = np.where(arr9_1 == 9)

max_idx9_4 = np.argmax(arr9_1)
print("\nTask 9 Results")
print("Sorted 1D =", sorted_arr9_1)
print("Sorted Columns =\n", sorted_cols9_2)
print("Index of 9 =", idx9_3)
print("Index of Maximum =", max_idx9_4)



Task 9 Results
Sorted 1D = [1 2 3 4 5 6 7 8 9]
Sorted Columns =
 [[30 20 10]
 [60 50 40]
 [90 80 70]]
Index of 9 = (array([4]),)
Index of Maximum = 4
